service: email-api

frameworkVersion: '4'

provider:
  name: aws
  runtime: python3.9
  region:  ap-south-1
  stage: dev
  environment:
    STAGE: ${self:provider.stage}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - ses:SendEmail
            - ses:SendRawEmail
          Resource: "*"

functions:
  sendEmail:
    handler: handler.send_email
    events:
      - httpApi:
          path: /send-email
          method: post
    environment:
      FROM_EMAIL: saketmeshram111@gmail.com 

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: false
    pythonBin: python